### ISSUE TITLE
Creation of a new Makefile.nopkg in the Models to backwards compatibility 

### ISSUE THREAD

**Issue by maxiwell** [ArchC/ArchC#11]
In new master branch, the ArchC uses PKG_CONFIG to resolve 'include's and 'lib's PATH. If your machine does not have the PKG package, you will fail to compile the Model. So, a new Makefile called Makefile.nopkg keep the old version of Makefile.archc without PKG_CONFIG.

**Comment by tiagofalcao** [comment]
The current Makefile.archc is portable, if you generate one processor in one machine you can copy the files to another and the Makefile.archc is the same.

With the env.sh all users can easily set the environment to build with current Makefile.archc.

I don't like the idea of maintain two files to same thing.

**Comment by maxiwell** [comment]
All recently systems does have pkg-config package? My concern is when the machine does not have the 'pkg_config'. A ./configure --disable-pkgconfig could be a solution. A similar example happens in HLTrace. To compile all ArchC source code, the 'libdw' is required to HLTrace. But if you want compile without it, you can be ./configure --disable-hlt.
