### ISSUE TITLE
Standalone simulator with cache doesn't compiles

### ISSUE THREAD

**Issue by maxiwell** [ArchC/ArchC#17]
In a standalone simulator, the memory is instantiated inside the model using the class **ac_storage**. With the cache, all write and read operation to **ac_storage** calls the methods **read_dir** and **write_dir**, but **ac_storage** doesn't implements this methods. These directory operations should be implemented in the last level memory (e.g. RAM)?

**Comment by lianaduenha** [comment]
The current code of cache is not ready yet. The coherence is an issue only for multiprocessor platform, so the Dir access is not necessary for standalone simulators. 

My idea is to maintain the cache (for data and instructions) without the Dir access, by default. We can enable  the Dir access just in case of using the processor in a "platform" environment.  Although, I don't know if there is a flag for this in the ArchC compiling process.
