### ISSUE TITLE
Generating a model without -abi yields unusable code

### ISSUE THREAD

**Issue by rafaelauler** [ArchC/ArchC#22]
-abi is the flag responsible for activating the "xxx_syscall" class, where xxx is the model name. This suggests that -abi is optional. However, when generating the simulator without -abi, the model fails to compile with the following error:

xxx.cpp:996:7: error: ‘class xxx_parms::xxx_isa’ has no member named ‘syscall’

I think this flag should be dropped and the syscall class always generated.

**Comment by maxiwell** [comment]
I agree. If necessary, in the future a new flag '--no-abi' could be added.

**Comment by tiagofalcao** [comment]
https://github.com/ArchC/ArchC/commit/b24f253b7f7f00f5c55f75f1cd20a9d8f40f0a88
