### ISSUE TITLE
acsim -dy does not work 

### ISSUE THREAD

**Issue by Pavani14** [ArchC/ArchC#23]
on doing acsim mips.ac -abi -dy followed by make gives an error.

**Comment by maxiwell** [comment]
This bug is similar to #7. The **commit_delays** method was moved from ac_{regbank, reg, storage} to ac_memport, but the only ac_storage is compatible with ac_memport. When the ac_{reg, regbank} call it, the error below appear:

XXX has no member named ‘commit_delays’

**Comment by maxiwell** [comment]
It was fixed in the commit https://github.com/ArchC/ArchC/commit/9c15705615393064f8152139cdab9486f9166dc0
