### ISSUE TITLE
Coding style

### ISSUE THREAD

**Issue by tiagofalcao** [ArchC/ArchC#3]
The ArchC need a official code style.

I suggest use one of the existing at clang-format(-3.7):
LLVM, Google, Chromium, Mozilla, WebKit

I recommend Google or LLVM code styles.

After defined, we need apply in all source and refuse patches that don't follow it.

**Comment by maxiwell** [comment]
My vote is to LLVM code styles.

**Comment by tiagofalcao** [comment]
Very reasonable use the LLVM, as architecture and compilers works together.

But I want a great tool like Google's cpplint.

**Comment by rafaelauler** [comment]
Just clang-format the code and use http://clang.llvm.org/extra/clang-tidy/
