### ISSUE TITLE
Problems in compiling standalone models with caches

### ISSUE THREAD

**Issue by lianaduenha** [ArchC/ArchC#33]
The syntax to instantiate caches in a standalone processor model is:

Using mips.ac as an example: 

AC_ARCH(mips){
  ac_mem   DM:512M;
  ac_icache   IC("2w", 64, 8, "wt", "random");
  ac_dcache   DC("2w", 64, 8, "wt", "random");
   ....
  ARCH_CTOR(mips) {
   ac_isa("mips_isa.ac");
   set_endian("big");
   IC.bindTo(DM);
   DC.bindTo(DM);
  };
};

If we connect an external memory to the model, we may exchange ac_mem by ac_tlm2_port  (or ac_tlm2_nb_port for non-blocking transport).  

When we use the model inside platforms (MPSoCBench platforms, for example), the connection processor->caches->external memory is working correctly.

The problem is that the standalone model does not compile, and we have to investigate the cause. I suggest that the interface between the ac_mem and cache models was not properly validated.

**Comment by maxiwell** [comment]
A BugFix was submitted in the PR #35 
Check if all is fine
