### ISSUE TITLE
"id" register in the models must exist

### ISSUE THREAD

**Issue by maxiwell** [ArchC/ArchC#45]
If I create a new model without "id" register, the source code generated by "acsim" will not compile. The reason is the function `getId()` hardcoded in the `model_arch.H` that accesses an object called `id`. 

No, the source code generated by "acsim" can NOT expect a register with a specific name because the designer may use other names. Maybe a "model_isa_helper" file should be used to implement the  `getId()` function. 

Another solution is to create a new reserved word in the ArchC to set an identifier in the model, like  `ac_id` instead of `ac_reg`. The `getId()` should be added in the `model_arch.H` only if the `ac_id` appear in the `model.ac`.

**Comment by rafaelauler** [comment]
I noticed this a while ago. I thought it was some decision I missed in the past. I agree it's really bad to expect a specific register to be present.

First of all, what is this getId() used for?

**Comment by rjazevedo** [comment]
I do not know. But I agree that we can not ask for a specific register name. If this register is required, it should be embedded by default, like ac_pc.
